# Generated by Django 4.2 on 2024-08-31 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=255, verbose_name='Issue Name')),
                ('isin', models.CharField(max_length=255, verbose_name='ISIN')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('coupon_type', models.CharField(choices=[('FIXED_RATE', 'Fixed Rate'), ('FLOATING_RATE', 'Floating Rate'), ('ZERO_COUPON', 'Zero Coupon'), ('STEP_UP', 'Step Up')], max_length=255, verbose_name='Coupon Type')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Interest Rate')),
                ('coupon_frequency_in_months', models.PositiveIntegerField(verbose_name='Coupon Frequency in Months')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('maturity_date', models.DateField(verbose_name='Maturity Date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bonds', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
            },
        ),
    ]
